{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"GHG_Emissions_Totals\",\"ESG Global Company\",\"GHG_Targets\",\"VIEWS vwPbiCompany\",\"Query1\",\"Errors in ESG Global Company\",\"Errors in ESG Global Company (2)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1052.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Errors in ESG Global Company",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "Source = #\"ESG Global Company\",\r",
          "  #\"Detected Type Mismatches\" = let\r",
          "    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Source, Table.ColumnsOfType(Source, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),\r",
          "    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),\r",
          "    fieldNames = Record.FieldNames(recordTypeFields),\r",
          "    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),\r",
          "    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = \"The type of the value does not match the type of the column.\", Detail = v], fieldTypes{i}})\r",
          "in\r",
          "    Table.TransformColumns(Source, pairs),\r",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Detected Type Mismatches\", \"Row Number\" ,1),\r",
          "  #\"Kept Errors\" = Table.SelectRowsWithErrors(#\"Added Index\", {\"Name\", \"Data\", \"Schema\", \"Item\", \"Kind\", \"SEC/NON-SEC\", \"SN Index\"}),\r",
          "  #\"Reordered Columns\" = Table.ReorderColumns(#\"Kept Errors\", {\"Row Number\", \"Name\", \"Data\", \"Schema\", \"Item\", \"Kind\", \"SEC/NON-SEC\", \"SN Index\"})\r",
          "in\r",
          "  #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "fa54bb61-76a4-4de7-a727-4170ad6e236a",
        "queryGroup": "Query Errors - 1/7/2024 4:19:27 PM"
      },
      {
        "name": "Errors in ESG Global Company (2)",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "Source = #\"ESG Global Company\",\r",
          "  #\"Detected Type Mismatches\" = let\r",
          "    tableWithOnlyPrimitiveTypes = Table.SelectColumns(Source, Table.ColumnsOfType(Source, {type nullable number, type nullable text, type nullable logical, type nullable date, type nullable datetime, type nullable datetimezone, type nullable time, type nullable duration})),\r",
          "    recordTypeFields = Type.RecordFields(Type.TableRow(Value.Type(tableWithOnlyPrimitiveTypes))),\r",
          "    fieldNames = Record.FieldNames(recordTypeFields),\r",
          "    fieldTypes = List.Transform(Record.ToList(recordTypeFields), each [Type]),\r",
          "    pairs = List.Transform(List.Positions(fieldNames), (i) => {fieldNames{i}, (v) => if v = null or Value.Is(v, fieldTypes{i}) then v else error [Message = \"The type of the value does not match the type of the column.\", Detail = v], fieldTypes{i}})\r",
          "in\r",
          "    Table.TransformColumns(Source, pairs),\r",
          "  #\"Added Index\" = Table.AddIndexColumn(#\"Detected Type Mismatches\", \"Row Number\" ,1),\r",
          "  #\"Kept Errors\" = Table.SelectRowsWithErrors(#\"Added Index\", {\"Name\", \"Data\", \"Schema\", \"Item\", \"Kind\", \"SEC/NON-SEC\", \"SN Index\"}),\r",
          "  #\"Reordered Columns\" = Table.ReorderColumns(#\"Kept Errors\", {\"Row Number\", \"Name\", \"Data\", \"Schema\", \"Item\", \"Kind\", \"SEC/NON-SEC\", \"SN Index\"})\r",
          "in\r",
          "  #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "26b54324-e740-428d-8c29-6e7cd8c4aa2a",
        "queryGroup": "Query Errors - 1/7/2024 4:26:58 PM"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "description": "Errors in queries that were loaded on 1/7/2024 4:19:27 PM.",
        "folder": "Query Errors - 1/7/2024 4:19:27 PM"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "description": "Errors in queries that were loaded on 1/7/2024 4:26:58 PM.",
        "folder": "Query Errors - 1/7/2024 4:26:58 PM"
      }
    ],
    "relationships": [
      {
        "name": "0d033e36-35bb-43f5-857d-c53beee2d10b",
        "fromColumn": "UpdatedDate",
        "fromTable": "GHG_Emissions_Totals",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_223b7b37-87b5-4c2d-bc6e-bb12a0ef9025"
      },
      {
        "name": "91f58564-66dd-4fea-80fe-2403d0bddaa9",
        "fromColumn": "UpdatedDate",
        "fromTable": "GHG_Targets",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_518eaaf6-35e7-457a-934f-c9c1c882792d"
      },
      {
        "name": "a99a6f95-064b-4237-afca-04c23c92214c",
        "fromColumn": "GlobalCompanyId",
        "fromTable": "GHG_Emissions_Totals",
        "toColumn": "GlobalCompanyId",
        "toTable": "VIEWS vwPbiCompany"
      },
      {
        "name": "6ccc1900-b77b-43ce-881f-38d325d30f65",
        "fromColumn": "GlobalCompanyId",
        "fromTable": "GHG_Targets",
        "toColumn": "GlobalCompanyId",
        "toTable": "VIEWS vwPbiCompany"
      },
      {
        "name": "96e59c14-fbfb-4ae2-895b-c6024ba6e1e9",
        "fromColumn": "UpdatedDate",
        "fromTable": "Query1",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ed87b76b-8375-4c0c-9013-b9f8d4bca5f8"
      },
      {
        "name": "29cde3c0-1af2-4cc0-8033-e408c84dc984",
        "fromColumn": "GlobalCompanyId",
        "fromTable": "Query1",
        "toColumn": "GlobalCompanyId",
        "toTable": "VIEWS vwPbiCompany"
      },
      {
        "name": "eb0e74ac-7cca-4a41-a10b-dc55fb819f69",
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "GlobalCompanyId",
        "fromTable": "ESG Global Company",
        "toColumn": "GlobalCompanyId",
        "toTable": "VIEWS vwPbiCompany"
      },
      {
        "name": "b29684b4-248f-40b6-ac1a-b1ed9c48b10d",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "GlobalCompanyId",
        "fromTable": "GHG_Emissions_Totals",
        "isActive": false,
        "toColumn": "GlobalCompanyId",
        "toTable": "ESG Global Company"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "GHG_Emissions_Totals",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GlobalCompanyId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0d0168a1-d74e-4940-870a-21de2374e5ea",
            "sourceColumn": "GlobalCompanyId",
            "summarizeBy": "none"
          },
          {
            "name": "FieldId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e6cca35e-5cfc-4b06-ab15-e5d9ad0a966b",
            "sourceColumn": "FieldId",
            "summarizeBy": "none"
          },
          {
            "name": "ReportedYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "lineageTag": "99a52b58-e39a-4e13-8c66-18dc5de73d16",
            "sourceColumn": "ReportedYear",
            "summarizeBy": "none"
          },
          {
            "name": "UpdatedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2a940902-c5ae-42b6-9670-30afbad4fd8a",
            "sourceColumn": "UpdatedDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_223b7b37-87b5-4c2d-bc6e-bb12a0ef9025"
                },
                "isDefault": true,
                "relationship": "0d033e36-35bb-43f5-857d-c53beee2d10b"
              }
            ]
          },
          {
            "name": "FieldName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fedc5d2f-7ab7-4d68-8abd-e882493805ec",
            "sourceColumn": "FieldName",
            "summarizeBy": "none"
          },
          {
            "name": "VendorFieldName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2e8dc4a-d13d-432a-85bf-8ec0193bdd8a",
            "sourceColumn": "VendorFieldName",
            "summarizeBy": "none"
          },
          {
            "name": "VendorId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "238ecfab-72fd-4939-bb32-a8caca6ef28a",
            "sourceColumn": "VendorId",
            "summarizeBy": "count"
          },
          {
            "name": "KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4595cfcd-2655-4a8a-a84f-9055509cb01a",
            "sourceColumn": "KPI",
            "summarizeBy": "none"
          },
          {
            "name": "YearCheck",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "expression": "(GHG_Emissions_Totals[Max Year]=GHG_Emissions_Totals[ReportedYear])",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isDataTypeInferred": true,
            "lineageTag": "cd6ae216-795e-4f65-810f-b1523d936e45",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "FieldValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a70aa68c-a6be-466d-ba0e-44295c7451e8",
            "sourceColumn": "FieldValue",
            "summarizeBy": "none"
          },
          {
            "name": "Measure",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "996f4ca4-578c-4ff4-a309-682a859da94a",
            "sourceColumn": "Measure",
            "summarizeBy": "sum"
          },
          {
            "name": "Measure2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50873846-8d98-4b02-a4f6-9eef9138631b",
            "sourceColumn": "Measure2",
            "summarizeBy": "none"
          },
          {
            "name": "Metric_Company",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "[Measure] & \" - \" & 'ESG Global Company'[Company_name]",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "dc67c463-8da1-4341-8bcb-1924def9adf5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "c4c77e8c-3210-4d4d-b3f8-531d8a33d13b",
        "measures": [
          {
            "name": "No Data",
            "expression": "\"*No Data Available\"",
            "lineageTag": "1937d50a-73a4-4e94-ac67-c917edb1168e"
          },
          {
            "name": "NoDataAVail",
            "expression": "\"*No data available\"",
            "lineageTag": "a720c7a3-c488-4f13-97c2-fdc5b1a61102"
          },
          {
            "name": "FieldValuesComparison",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(VALUE('ESG Global Company'[Company_name]),",
              "FILTER('ESG Global Company',",
              "'ESG Global Company'[Company Vendor] IN {SELECTEDVALUE(Baseline[Company Vendor]),SELECTEDVALUE(Peer[Company Vendor])}",
              "))"
            ],
            "lineageTag": "acb4568d-bbe0-48df-972c-dd33f32039dd"
          },
          {
            "name": "SelectedValuesSum",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    VALUE('ESG Global Company'[Company_name]),",
              "    'ESG Global Company'[Company Vendor] = SELECTEDVALUE(Baseline[Company Vendor]) ||",
              "    'ESG Global Company'[Company Vendor] = SELECTEDVALUE(Baseline[Company Vendor])",
              ")"
            ],
            "lineageTag": "e2a3dd7b-d66c-4937-bdda-8833908068f3"
          },
          {
            "name": "Max Year",
            "expression": "MAX(GHG_Emissions_Totals[ReportedYear])",
            "lineageTag": "6a3135c7-0a96-4999-885b-308c8b8782d4"
          },
          {
            "name": "DisplayedMetric",
            "expression": [
              "",
              "VAR ReportedTotal =",
              "    CALCULATE (",
              "        SUM ( GHG_Emissions_Totals[Measure] ),",
              "        GHG_Emissions_Totals[KPI] = \"Reported Scope 1\"",
              "    )",
              "VAR EstimatedTotal =",
              "    CALCULATE (",
              "        SUM (  GHG_Emissions_Totals[Measure] ),",
              "        GHG_Emissions_Totals[KPI] = \"Estimated Scope 1\"",
              "    )",
              "RETURN",
              "    IF (",
              "        ReportedTotal > 0,",
              "        IF (",
              "            OR ( ReportedTotal = 0, ISBLANK ( ReportedTotal ) ),",
              "            \"Estimated Scope 1 Total(MtCO2e)\",",
              "            \"Reported Scope 1 Total(MtCO2e)\"",
              "        ),",
              "        IF (",
              "            AND ( ReportedTotal = 0, ISBLANK ( ReportedTotal ) ),",
              "            IF ( EstimatedTotal > 0, \"Estimated Scope 1 Total(MtCO2e)\", BLANK () ),",
              "            \"Reported Scope 1 Total(MtCO2e)\"",
              "        )",
              "    )",
              ""
            ],
            "lineageTag": "a377dff9-9d18-4055-9878-9faa2e6f7f9e"
          },
          {
            "name": "TotalScope1emissionsBaseline",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( GHG_Emissions_Totals[FieldValue] ),",
              "    'ESG Global Company'[GlobalCompanyId] = SELECTEDVALUE ( Baseline[GID])",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "6dd85b0a-a319-4f6e-8a93-924fe502d5ee"
          },
          {
            "name": "SumMetricValue",
            "expression": [
              "",
              "VAR ReportedTotal =",
              "    CALCULATE (",
              "        SUMX (",
              "            FILTER (",
              "                GHG_Emissions_Totals,",
              "                GHG_Emissions_Totals[KPI] = \"Reported Scope 1 Total\"",
              "            ),",
              "            VALUE ( GHG_Emissions_Totals[Measure] )",
              "        )",
              "    )",
              "VAR EstimatedTotal =",
              "    CALCULATE (",
              "        SUMX (",
              "            FILTER (",
              "                GHG_Emissions_Totals,",
              "                GHG_Emissions_Totals[KPI] = \"Estimated Scope 1 Total\"",
              "            ),",
              "            VALUE ( GHG_Emissions_Totals[Measure] )",
              "        )",
              "    )",
              "RETURN",
              "    IF (",
              "        ReportedTotal > 0",
              "            || EstimatedTotal > 0,",
              "        IF ( ReportedTotal > 0, ReportedTotal, EstimatedTotal ),",
              "        BLANK ()",
              "    )",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ba8c62d3-5acc-4c9f-b2ca-dd39f727863c"
          },
          {
            "name": "Filtered_Values",
            "expression": [
              "",
              "CALCULATE (",
              "    VALUES ( GHG_Emissions_Totals[Measure2] ),",
              "    GHG_Emissions_Totals[KPI] = \"Calculation Period Start Date\"",
              "        || GHG_Emissions_Totals[KPI] = \"Calculation Period End Date\"",
              ")",
              ""
            ],
            "lineageTag": "f3e73a61-acbe-4cef-b919-3cc08994e0b7"
          },
          {
            "name": "Earliest_Start_Date",
            "expression": [
              "",
              "CALCULATE (",
              "    MIN ( GHG_Emissions_Totals[Measure2] ),",
              "    GHG_Emissions_Totals[KPI] = \"Calculation Period Start Date\",",
              "    GHG_Emissions_Totals[Measure2] <> \"*\",",
              "    FILTER ( ALL ( Baseline ), NOT ( ISBLANK ( [Filtered_Values] ) ) )",
              ")",
              ""
            ],
            "lineageTag": "3ea14914-8255-4f1f-990a-7c5a7fedbbf3"
          },
          {
            "name": "Latest_End_Date",
            "expression": [
              "",
              "CALCULATE (",
              "    MAXX (",
              "        FILTER (",
              "            GHG_Emissions_Totals,",
              "           GHG_Emissions_Totals[KPI] = \"calculation_end_date\"",
              "                && NOT ( ISBLANK ( [Filtered_Values] ) ) && GHG_Emissions_Totals[Measure2]<>\"*\"",
              "        ), ",
              "        GHG_Emissions_Totals[Measure2]",
              "    )",
              ")",
              ""
            ],
            "lineageTag": "ca74b459-bc12-4562-ad67-c017fb8b26e7"
          },
          {
            "name": "Calculation_Period",
            "expression": [
              "",
              "IF (",
              "    NOT ( ISBLANK ( [Earliest_Start_Date] ) ) && NOT ( ISBLANK ( [Latest_End_Date] ) ),",
              "    FORMAT ( [Earliest_Start_Date], \"YYYY-MM-DD\" ) & \" to \"",
              "        & FORMAT ( [Latest_End_Date], \"YYYY-MM-DD\" ),",
              "    \"*\"",
              ")",
              ""
            ],
            "lineageTag": "487dc965-4fdc-4d2f-a88d-bbf1dfa73222"
          },
          {
            "name": "Calculation_Period2",
            "expression": [
              "",
              "    FORMAT (MIN(GHG_Emissions_Totals[Measure2]), \"YYYY-MM-DD\" ) & \" to \"",
              "        & FORMAT ( MAX(GHG_Emissions_Totals[Measure2]), \"YYYY-MM-DD\" )",
              ""
            ],
            "lineageTag": "06caf866-30c7-4845-bb9d-f61c76ec5265"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(COUNT(GHG_Emissions_Totals[KPI])< 1, \"*\",SUM(GHG_Emissions_Totals[Measure]))",
            "lineageTag": "465c0831-ce3f-43b5-bb20-5c7511dedbce"
          },
          {
            "name": "SelectedCompany",
            "expression": [
              "",
              "",
              "    CONCATENATEX (",
              "        VALUES ( 'ESG Global Company'[CompanyName] ),",
              "        'ESG Global Company'[CompanyName],",
              "        \", \"",
              "    )",
              ""
            ],
            "lineageTag": "2bf0b00f-da8d-4dae-896b-3145511137f1"
          },
          {
            "name": "MissingDataMessage",
            "expression": [
              "",
              "IF (",
              "    COUNT ( GHG_Emissions_Totals[KPI] ) < 1,",
              "    CONCATENATEX (",
              "        VALUES ( 'GHG_Emissions_Totals'[Metric_Company] ),",
              "        \"'\" & SELECTEDVALUE ( 'ESG Global Company'[CompanyName] ) & \"' data is not available for \"",
              "            & SELECTEDVALUE ( 'ESG Global Company'[CompanyName] ) & \"'\"",
              "    ),",
              "    BLANK ()",
              ")",
              ""
            ],
            "lineageTag": "5b99fedb-dccf-4569-bd82-f486f71b8f5a"
          },
          {
            "name": "TestMeasure",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Value],FILTER('ESG Global Company','ESG Global Company'[CompanyName] IN {ALLSELECTED(Peer[Cname]),SELECTEDVALUE(Baseline[Cname])}))",
            "lineageTag": "3eb7dca5-0c35-4984-8c9d-93ad7218ba06"
          },
          {
            "name": "MaxSumValues",
            "expression": [
              "",
              "MAXX (",
              "    SUMMARIZE (",
              "        GHG_Emissions_Totals,",
              "        'ESG Global Company'[CompanyName],",
              "        \"TotalValue\", SUM (GHG_Emissions_Totals[Measure] )",
              "    ),",
              "    [TotalValue]",
              ")",
              ""
            ],
            "formatString": "0",
            "lineageTag": "fb74b211-2a0a-4df2-91ab-aa28225877da"
          },
          {
            "name": "AXIS  SYNC",
            "lineageTag": "bc176443-1e67-4012-af93-67a307d3e2e8"
          },
          {
            "name": "Metric Value",
            "expression": "IF(COUNT(GHG_Emissions_Totals[KPI])< 1,0,SUM(GHG_Emissions_Totals[Measure]))",
            "formatString": "0",
            "lineageTag": "da09c780-ba41-4d43-afe4-887819d98aec"
          },
          {
            "name": "NoData_Company",
            "expression": [
              "",
              "IF([Metric Value]= 0,",
              "CONCATENATEX (",
              "        VALUES ( 'ESG Global Company'[CompanyName] ),",
              "        'ESG Global Company'[CompanyName],",
              "        \", \"",
              "    ),\"*\")"
            ],
            "lineageTag": "314621c8-107d-4f82-a80e-1bae9644d29a"
          }
        ],
        "partitions": [
          {
            "name": "GHG_Emissions_Totals",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"d1esginsightssqluse2.database.windows.net\", \"ESGVendorDB\", ",
                "    [Query=\"SELECT *,",
                "case",
                "when FieldId ='500' then 'Reported Scope 1'",
                "when FieldId  ='503'  then 'Reported Market-Based Scope 2'",
                "when FieldId  ='504'  then 'Reported Location-Based Scope 2'",
                "when FieldId  ='530'  then 'Cleaned and Applicable Scope 3 Total'",
                "when FieldId  ='664'  then 'Calculation Period Start Date'",
                "when FieldId  ='665'  then 'Calculation Period End Date'",
                "when FieldId  ='501'  then 'Estimated Scope 1'",
                "else ' ' end as KPI",
                "FROM [VIEWS].[vwPbiGHGEmissionsTotalsFieldValue]\t\"]),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(Source, \"Measure2\", each if [FieldValue] = \"Entity deemed question not applicable\" then \"*\" else [FieldValue]),",
                "    #\"Added Conditional Column\" = Table.AddColumn(#\"Added Conditional Column1\", \"Measure\", each if [KPI] = \"Calculation Period Start Date\" then 0 else if [KPI] = \"Calculation Period End Date\" then 0 else [FieldValue]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Conditional Column\",{{\"Measure\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_d61b4a97-d6bb-4c99-9730-8e3a25745093",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b552400f-7593-4539-bd73-a943a4b78a86",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1b836383-d76c-40b2-bf17-33315beea2bf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ba54e31f-561e-4f35-9646-2c3d2fbd9957",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d1556654-5811-4cd0-b6ed-9a471038402f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "a18f2dc4-c0bf-4864-8aa3-a6c4ea672480",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "69af87ac-184b-488d-9e89-2f9ddcc4214b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "79ae940f-0c15-481a-be37-33222853e140",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7d65a021-88d9-4e0b-97c8-aac61428c7a0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "cd4791bd-3a3b-45b6-bb24-17633dc06b07",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6ef2f651-608d-4699-a347-1d85c7d5fa18",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8797b56a-2615-4866-9be3-e1b86124fb87",
                "ordinal": 3
              }
            ],
            "lineageTag": "b01a4335-e7bf-4532-abb9-3a32b999a01b"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "8f84f33c-6b52-4058-9a5d-3bc3efb4616e",
        "partitions": [
          {
            "name": "DateTableTemplate_d61b4a97-d6bb-4c99-9730-8e3a25745093",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_223b7b37-87b5-4c2d-bc6e-bb12a0ef9025",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "692d97ea-1852-44c9-b834-e6b03a5d25d1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "97948bfb-49a2-4f04-8c50-30aafc21b23d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e97a6dd0-bfa5-4f94-9933-78fffcf187c0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2b9bb82a-d2b3-4a86-9041-21c86d1b2813",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "eaba8f91-e566-4fc7-845a-e0289533e34b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "e2bea09c-2670-442e-be76-2d7a9785fd25",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4583d59b-ee14-4964-9fd1-32646a08fc84",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a3a18e9d-7e66-42f8-97fa-e749233c49f2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c2ea2690-917a-4b2d-84aa-448dc40a2c1b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9840fbf7-0b65-4d6b-a26b-7f4877251ecc",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "04d93a06-83a8-4c8c-90fc-a92c33be259a",
                "ordinal": 3
              }
            ],
            "lineageTag": "d0a63713-ad3c-4e9b-856b-135f9caee697"
          }
        ],
        "isHidden": true,
        "lineageTag": "1e8371a2-9c45-481f-a6cb-4c1e1023c255",
        "partitions": [
          {
            "name": "LocalDateTable_223b7b37-87b5-4c2d-bc6e-bb12a0ef9025",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('GHG_Emissions_Totals'[UpdatedDate])), 1, 1), Date(Year(MAX('GHG_Emissions_Totals'[UpdatedDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "ESG Global Company",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Company Vendor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'ESG Global Company'[CompanyName] & \" - \" &'ESG Global Company'[VendorName] ",
            "isDataTypeInferred": true,
            "lineageTag": "d31c51fe-4801-4962-80e0-50ebfc6f3eca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "VendorName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "LEFT (",
              "    IF ( 'ESG Global Company'[IsCDPCompany], \"CDP,\", \"\" )",
              "        & IF ('ESG Global Company'[IsSNPCompany], \"S&P,\", \"\" )",
              "        & IF ( 'ESG Global Company'[IsRaterRankerCompany], \"SEC,\", \"\" )",
              "        & IF ('ESG Global Company'[IsMSCICompany], \"MSCI\", \"\" ),",
              "    LEN (",
              "        IF ( 'ESG Global Company'[IsCDPCompany], \"CDP,\", \"\" )",
              "            & IF ( 'ESG Global Company'[IsSNPCompany], \"S&P,\", \"\" )",
              "            & IF ( 'ESG Global Company'[IsRaterRankerCompany], \"SEC,\", \"\" )",
              "            & IF ('ESG Global Company'[IsMSCICompany], \"MSCI\", \"\" )",
              "    ) - 1",
              ")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "55dd58cd-0f6f-49c3-8b80-0a1334ce7559",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "IncludeCompany",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "expression": [
              "\r",
              "SWITCH (\r",
              "    TRUE (),\r",
              "    ISFILTERED ( Baseline )\r",
              "        && VALUES ( 'ESG Global Company'[GlobalCompanyId] ) IN VALUES ( Baseline[GID] ), 1,\r",
              "    ISFILTERED ( Peer )\r",
              "        && VALUES ( 'ESG Global Company'[GlobalCompanyId] ) IN VALUES ( Peer[GID] ), 1,\r",
              "    0\r",
              ")\r",
              ""
            ],
            "formatString": "0",
            "lineageTag": "2d6be945-1d6b-4a1a-afab-9a88f8ad73db",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "GlobalCompanyId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3d7fe8c-d806-4b46-a4e0-8e77348fd7da",
            "sourceColumn": "GlobalCompanyId",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "70ee2b53-48ae-463d-adbd-7aaa95d0149a",
            "sourceColumn": "CompanyName",
            "summarizeBy": "none"
          },
          {
            "name": "Ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32c7a5b6-98cb-4493-b968-a383be94cf08",
            "sourceColumn": "Ticker",
            "summarizeBy": "none"
          },
          {
            "name": "CountryCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f98e51e1-f7af-47a8-bba6-8ea985f5bc8f",
            "sourceColumn": "CountryCode",
            "summarizeBy": "none"
          },
          {
            "name": "IsMSCICompany",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "59ab20a1-903f-464f-84a6-bd5b9160f0a2",
            "sourceColumn": "IsMSCICompany",
            "summarizeBy": "none"
          },
          {
            "name": "IsRaterRankerCompany",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "a53cd5b3-c337-4aa5-a468-f8770db779d8",
            "sourceColumn": "IsRaterRankerCompany",
            "summarizeBy": "none"
          },
          {
            "name": "IsCDPCompany",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "e6ee37f0-6a50-4b83-bce6-1af90a66975f",
            "sourceColumn": "IsCDPCompany",
            "summarizeBy": "none"
          },
          {
            "name": "IsSNPCompany",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0fa045c1-5ab1-45d3-bb0c-084b7f361327",
            "sourceColumn": "IsSNPCompany",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "90d78cb3-96fa-4ddf-939e-a6ce39e3434d",
            "sourceColumn": "IndustryId",
            "summarizeBy": "count"
          },
          {
            "name": "MRFYMarketCap",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c83a0c23-670c-48f1-9fda-156369792545",
            "sourceColumn": "MRFYMarketCap",
            "summarizeBy": "sum"
          },
          {
            "name": "IndustryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38109727-ae86-4a60-8ba4-a879fa6c5100",
            "sourceColumn": "IndustryName",
            "summarizeBy": "none"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1efcc4e-ed88-4bdb-977b-89e93cffb5ea",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ab92e0e1-79fc-464d-b484-44e7457fd84f",
        "measures": [
          {
            "name": "Company_name",
            "expression": "SELECTEDVALUE('ESG Global Company'[CompanyName])",
            "lineageTag": "d9433e42-4f87-45b0-b3f4-9ade3aa6592d"
          },
          {
            "name": "Absolute Target",
            "expression": "\"Absolute Target\"",
            "lineageTag": "033fac73-06d9-4fcf-9c0f-b889bc1df398"
          },
          {
            "name": "BasePeerCompare1",
            "expression": [
              "",
              "CALCULATE(",
              "    'ESG Global Company'[Company_name],",
              "    FILTER(",
              "        'ESG Global Company',",
              "        'ESG Global Company'[Company_name] IN {SELECTEDVALUE('Peer'[Cname]),SELECTEDVALUE('VIEWS vwPbiCompany'[CompanyName])}))"
            ],
            "formatString": "0",
            "lineageTag": "dc58061f-e783-49bb-8b61-f21198f682ff"
          },
          {
            "name": "ColorByCompany",
            "expression": [
              "",
              "VAR SelectedCompanies =",
              "    VALUES ( 'ESG Global Company'[CompanyName] )",
              "VAR ColorList = {",
              "    \"#62B5E5\",",
              "    \"#005587\",",
              "    \"#FFE67F\",",
              "    \"#EC7016\",",
              "    \"#992165\",",
              "    \"#DCECC9\",",
              "    \"#CFBC98\",",
              "    \"#6E9368\",",
              "    \"#004F59\"",
              "}",
              "VAR CompanyCount =",
              "    COUNTROWS ( SelectedCompanies )",
              "RETURN",
              "    IF (",
              "        HASONEVALUE ( 'ESG Global Company'[CompanyName] ),",
              "        SWITCH (",
              "            VALUES ( 'ESG Global Company'[CompanyName] ),",
              "            \"Company1\", ColorList,",
              "            \"Company2\", ColorList,",
              "            \"Company3\", ColorList,",
              "            \"Company4\", ColorList,",
              "            \"Company5\", ColorList,",
              "            \"Company6\", ColorList,",
              "            \"Company7\", ColorList,",
              "            \"Company8\", ColorList,",
              "            \"Company9\", ColorList,",
              "            BLANK ()",
              "        ),",
              "        BLANK ()",
              "    )",
              ""
            ],
            "lineageTag": "e07d8de3-77ec-4321-8aa6-a67baa0fc3b0"
          },
          {
            "name": "SelectedGlobalCompanyId",
            "expression": [
              "",
              "VAR BaselineFilter =",
              "    VALUES ( Baseline[Company Vendor] )",
              "VAR PeerFilter =",
              "    VALUES ( Peer[Company Vendor] )",
              "RETURN",
              "    IF (",
              "        HASONEVALUE ( Baseline[Company Vendor] ) || HASONEVALUE ( Peer[Company Vendor] ),",
              "        UNION ( BaselineFilter, PeerFilter ),",
              "        BLANK ()",
              "    )",
              ""
            ],
            "lineageTag": "da12fef0-bc20-459a-8b24-0c6f70007917"
          }
        ],
        "partitions": [
          {
            "name": "ESG Global Company",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"d1esginsightssqluse2.database.windows.net\", \"ESGInsightsDB\"),",
                "    VIEWS_vwPbiCompany = Source{[Schema=\"VIEWS\",Item=\"vwPbiCompany\"]}[Data]",
                "in",
                "    VIEWS_vwPbiCompany"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "GHG_Targets",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GlobalCompanyId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "264502ca-3971-405d-89cd-a517d4395661",
            "sourceColumn": "GlobalCompanyId",
            "summarizeBy": "none"
          },
          {
            "name": "FieldId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1beb5a0e-4a60-4223-9f44-6108784ecf89",
            "sourceColumn": "FieldId",
            "summarizeBy": "count"
          },
          {
            "name": "FieldName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "659c77b0-e8cf-436f-82df-6bb1c3290c60",
            "sourceColumn": "FieldName",
            "summarizeBy": "none"
          },
          {
            "name": "VendorFieldName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46065dd9-bdd2-42a9-8f42-e3aca8151d56",
            "sourceColumn": "VendorFieldName",
            "summarizeBy": "none"
          },
          {
            "name": "FieldValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "df0df36d-3aed-4a04-844b-f5771e0f2651",
            "sourceColumn": "FieldValue",
            "summarizeBy": "none"
          },
          {
            "name": "ReportedYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d50f84ad-9cee-4cd5-be58-48e04ccda26a",
            "sourceColumn": "ReportedYear",
            "summarizeBy": "sum"
          },
          {
            "name": "UpdatedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "98c3fc32-8d72-49e8-a4f1-1920dcfa1698",
            "sourceColumn": "UpdatedDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_518eaaf6-35e7-457a-934f-c9c1c882792d"
                },
                "isDefault": true,
                "relationship": "91f58564-66dd-4fea-80fe-2403d0bddaa9"
              }
            ]
          },
          {
            "name": "VendorId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f6b9ec36-4ae6-4bae-a812-d7e294472101",
            "sourceColumn": "VendorId",
            "summarizeBy": "count"
          },
          {
            "name": "KPI",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d36a18ac-fe9e-4976-b0c9-6ef7f2616e02",
            "sourceColumn": "KPI",
            "summarizeBy": "none"
          },
          {
            "name": "TargetSequence",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6685a706-9d55-4eca-a68c-6176be5f1e0c",
            "sourceColumn": "TargetSequence",
            "summarizeBy": "none"
          },
          {
            "name": "TargetCountColumn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "436ba87b-9c83-4389-a31b-ebd06a36be98",
                "value": "{\"Expression\":\"\\nCALCULATE(\\n    COUNTROWS(\\n        VALUES('GHG_Targets'[TargetSequence])\\n    ),\\n    FILTER(\\n        'GHG_Targets',\\n        'ESG Global Company'[Company_name] = SELECTEDVALUE('ESG Global Company'[CompanyName])\\n&& 'GHG_Targets'[ReportedYear] = SELECTEDVALUE('GHG_Targets'[ReportedYear])\\n&& 'GHG_Targets'[KPI] <> \\\"Type of Targets in Reporting Year\\\"\\n    )\\n)\"}"
              },
              {
                "name": "277cc1b9-af89-4597-8e15-cacc25c0886b",
                "value": [
                  "A circular dependency was detected: GHG_Targets[Column].",
                  ""
                ]
              }
            ],
            "dataType": "int64",
            "isDataTypeInferred": true,
            "lineageTag": "19f8c679-215c-4769-82d4-1c98c0e0ba75",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "0890ff33-5a06-45d0-977e-5b92401fc54a",
        "measures": [
          {
            "name": "NoData",
            "expression": "\"* No Data Available\"",
            "lineageTag": "c67e5777-f89b-4c23-874f-92dc6a3f4adc"
          },
          {
            "name": "TargetCount",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS(",
              "        VALUES('GHG_Targets'[TargetSequence])",
              "    ),",
              "    FILTER(",
              "        'GHG_Targets',",
              "        'ESG Global Company'[Company_name] = SELECTEDVALUE('ESG Global Company'[CompanyName])",
              "&& 'GHG_Targets'[ReportedYear] = SELECTEDVALUE('GHG_Targets'[ReportedYear])",
              "&& 'GHG_Targets'[KPI] <> \"Type of Targets in Reporting Year\"",
              "    )",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "683ef8e4-38a7-4817-92de-23e7f1836ee7"
          },
          {
            "name": "SelectedCompanyFilter",
            "expression": [
              "",
              "",
              "    CONCATENATEX (",
              "        VALUES ( 'ESG Global Company'[CompanyName] ),",
              "        'ESG Global Company'[CompanyName],",
              "        \", \"",
              "    )"
            ],
            "lineageTag": "d29f374d-2db3-44c5-a205-f68b6a25445c"
          },
          {
            "name": "No_data",
            "expression": "if(ISBLANK(MAX(GHG_Targets[FieldValue])),\"*\",MAX(GHG_Targets[FieldValue]))",
            "lineageTag": "da3d995f-ff5e-4328-b80c-1f841f2b05e1"
          },
          {
            "name": "No_KPI",
            "expression": "if(ISBLANK(MAX(GHG_Targets[KPI])),\"*\",MAX(GHG_Targets[KPI]))",
            "lineageTag": "11c383f1-9b4a-4dd0-a3f7-3df30fb33ae8"
          },
          {
            "name": "SingleTarget",
            "expression": [
              "",
              "var SelectedCompany = SELECTEDVALUE('ESG Global Company'[CompanyName])",
              "var TargetCount = ",
              "CALCULATE(",
              "    COUNTROWS(",
              "        VALUES('GHG_Targets'[TargetSequence])",
              "    ),",
              "    FILTER(",
              "        'GHG_Targets',",
              "        'ESG Global Company'[Company_name] = SelectedCompany",
              "&& 'GHG_Targets'[ReportedYear] = SELECTEDVALUE('GHG_Targets'[ReportedYear])",
              "&& 'GHG_Targets'[KPI] <> \"Type of Targets in Reporting Year\"",
              "    )",
              ")",
              "return",
              "IF(TargetCount = 1, 1,0)"
            ],
            "formatString": "0",
            "lineageTag": "00be7364-edfa-4568-bc3e-7cfd7b311c62"
          },
          {
            "name": "SelectedTCount",
            "expression": "int(ALLSELECTED(targetc]))",
            "lineageTag": "b437431e-e675-432d-9e52-3800c254be85"
          },
          {
            "name": "MultiTarget",
            "expression": [
              "",
              "var SelectedCompany = SELECTEDVALUE('ESG Global Company'[CompanyName])",
              "var TargetCount = ",
              "CALCULATE(",
              "    COUNTROWS(",
              "        VALUES('GHG_Targets'[TargetSequence])",
              "    ),",
              "    FILTER(",
              "        'GHG_Targets',",
              "        'ESG Global Company'[Company_name] = SelectedCompany",
              "&& 'GHG_Targets'[ReportedYear] = SELECTEDVALUE('GHG_Targets'[ReportedYear])",
              "&& 'GHG_Targets'[KPI] <> \"Type of Targets in Reporting Year\"",
              "    )",
              ")",
              "return",
              "IF(TargetCount > 1, 1,0)"
            ],
            "formatString": "0",
            "lineageTag": "9fb90dc4-5455-4b10-acde-aedded247e51"
          }
        ],
        "partitions": [
          {
            "name": "GHG_Targets",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"d1esginsightssqluse2.database.windows.net\", \"ESGVendorDB\"),",
                "    VIEWS_vwPbiGHGTargetsFieldValue = Source{[Schema=\"VIEWS\",Item=\"vwPbiGHGTargetsFieldValue\"]}[Data],",
                "    #\"Added Conditional Column\" = Table.AddColumn(VIEWS_vwPbiGHGTargetsFieldValue, \"Custom\", each if Text.Contains([FieldName], \"TargetedReductionPercentage\") then \"Targeted Emissions Reduction %\" else if Text.Contains([FieldName], \"BaseYear\") then \"Base Year\" else if Text.Contains([FieldName], \"TargetYear\") then \"Target Year\" else if Text.Contains([FieldName], \"ScienceBasedTargets\") then \"SBTi Alignment\" else if Text.Contains([FieldName], \"ScopeOfTarget\") then \"Scope of Target\" else \"Type of Targets in Reporting Year\"),",
                "    #\"Added Conditional Column1\" = Table.AddColumn(#\"Added Conditional Column\", \"Custom.1\", each if Text.Contains([FieldName], \"Abs15\") then \"Target 15\" else if Text.Contains([FieldName], \"Abs14\") then \"Target 14\" else if Text.Contains([FieldName], \"Abs13\") then \"Target 13\" else if Text.Contains([FieldName], \"Abs12\") then \"Target 12\" else if Text.Contains([FieldName], \"Abs11\") then \"Target 11\" else if Text.Contains([FieldName], \"Abs10\") then \"Target 10\" else if Text.Contains([FieldName], \"Abs9\") then \"Target 9\" else if Text.Contains([FieldName], \"Abs8\") then \"Target 8\" else if Text.Contains([FieldName], \"Abs7\") then \"Target 7\" else if Text.Contains([FieldName], \"Abs6\") then \"Target 6\" else if Text.Contains([FieldName], \"Abs5\") then \"Target 5\" else if Text.Contains([FieldName], \"Abs4\") then \"Target 4\" else if Text.Contains([FieldName], \"Abs3\") then \"Target 3\" else if Text.Contains([FieldName], \"Abs2\") then \"Target 2\" else if Text.Contains([FieldName], \"Abs1\") then \"Target 1\" else \"*\"),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Added Conditional Column1\",{{\"Custom\", \"KPI\"}, {\"Custom.1\", \"TargetSequence\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_518eaaf6-35e7-457a-934f-c9c1c882792d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2fa5b8f9-7026-44db-8d23-10758d1a7fa6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5755a640-00db-471c-b7bc-d3a66144cb7e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b90c90de-e603-47f9-aca2-3c5a3e940dd3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1ff57a22-ec2c-4005-ae48-e7410ec1d193",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "77bb3089-346d-496b-9321-520e9cff0eef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2ab5e13e-5260-420c-a76b-4990ad63cbce",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "2709b3d6-cbee-4931-bd63-3697c889cd97",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7cf3da14-1861-4a68-a7b6-ebf0ee622b86",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "342089ae-0c23-4d9f-aab8-8801255a79d1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f676ef27-4067-411c-89c7-371cd9eee9f2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "208c5523-6172-423a-9579-c716edb20fa8",
                "ordinal": 3
              }
            ],
            "lineageTag": "1b2c5178-9c84-47df-80c8-b347d6bf173d"
          }
        ],
        "isHidden": true,
        "lineageTag": "de6ad574-2b76-4c95-ae08-bab6a14873ef",
        "partitions": [
          {
            "name": "LocalDateTable_518eaaf6-35e7-457a-934f-c9c1c882792d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('GHG_Targets'[UpdatedDate])), 1, 1), Date(Year(MAX('GHG_Targets'[UpdatedDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "VIEWS vwPbiCompany",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GlobalCompanyId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "372cab84-fa38-4d72-998f-a10ec29933e2",
            "sourceColumn": "GlobalCompanyId",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6d9db4e-0037-4e05-af23-924db2b224a9",
            "sourceColumn": "CompanyName",
            "summarizeBy": "none"
          },
          {
            "name": "Ticker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2c394067-f4e4-4d99-abd4-aa32f034dbe9",
            "sourceColumn": "Ticker",
            "summarizeBy": "none"
          },
          {
            "name": "CountryCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f3022de-e4a9-4a69-9734-05b40611d6f9",
            "sourceColumn": "CountryCode",
            "summarizeBy": "none"
          },
          {
            "name": "IsMSCICompany",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "b3a907eb-dd6d-4fd7-ae77-076a0038c5d9",
            "sourceColumn": "IsMSCICompany",
            "summarizeBy": "none"
          },
          {
            "name": "IsRaterRankerCompany",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "abe502aa-37af-4be1-a10d-b3bb0996a687",
            "sourceColumn": "IsRaterRankerCompany",
            "summarizeBy": "none"
          },
          {
            "name": "IsCDPCompany",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8bf49403-bbbe-408c-9cb6-272691b68299",
            "sourceColumn": "IsCDPCompany",
            "summarizeBy": "none"
          },
          {
            "name": "IsSNPCompany",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "6e7b6050-b466-4b18-8e68-a82814dbea89",
            "sourceColumn": "IsSNPCompany",
            "summarizeBy": "none"
          },
          {
            "name": "IndustryId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9cba59c5-f737-49e0-9bdc-2c54a0123185",
            "sourceColumn": "IndustryId",
            "summarizeBy": "count"
          },
          {
            "name": "MRFYMarketCap",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ecea2c5f-cecf-49e1-afbb-58d1a32d76c4",
            "sourceColumn": "MRFYMarketCap",
            "summarizeBy": "sum"
          },
          {
            "name": "IndustryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cab983a3-83dc-454c-9709-02253a9c6df8",
            "sourceColumn": "IndustryName",
            "summarizeBy": "none"
          },
          {
            "name": "Sector",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "554e29fc-0119-464c-89bc-608043c49771",
            "sourceColumn": "Sector",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2571123b-018e-4fd0-be80-540fcc55f9be",
        "partitions": [
          {
            "name": "VIEWS vwPbiCompany",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"d1esginsightssqluse2.database.windows.net\", \"ESGInsightsDB\"),",
                "    VIEWS_vwPbiCompany = Source{[Schema=\"VIEWS\",Item=\"vwPbiCompany\"]}[Data]",
                "in",
                "    VIEWS_vwPbiCompany"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Query1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CDPFieldValueTrackingId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "34c4958e-4a14-492f-a65e-d3539feea5aa",
            "sourceColumn": "CDPFieldValueTrackingId",
            "summarizeBy": "count"
          },
          {
            "name": "GlobalCompanyId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7734e05-7d6c-4d3c-ade1-e162f0fd0583",
            "sourceColumn": "GlobalCompanyId",
            "summarizeBy": "none"
          },
          {
            "name": "FieldId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "43719747-783d-4acd-b2c8-df953ebdd3d0",
            "sourceColumn": "FieldId",
            "summarizeBy": "count"
          },
          {
            "name": "FieldValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75069bbc-c01d-4108-a4d7-637f7eb4cb66",
            "sourceColumn": "FieldValue",
            "summarizeBy": "none"
          },
          {
            "name": "ReportedYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "361f4957-6b1e-4fd4-8bd7-adb276fbbe11",
            "sourceColumn": "ReportedYear",
            "summarizeBy": "sum"
          },
          {
            "name": "UpdatedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "2d81f7c8-b2e5-4616-bcb4-7fa2a14f14a3",
            "sourceColumn": "UpdatedDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ed87b76b-8375-4c0c-9013-b9f8d4bca5f8"
                },
                "isDefault": true,
                "relationship": "96e59c14-fbfb-4ae2-895b-c6024ba6e1e9"
              }
            ]
          },
          {
            "name": "FieldName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28f4662e-deee-46f2-a21f-d925dba63a97",
            "sourceColumn": "FieldName",
            "summarizeBy": "none"
          },
          {
            "name": "VendorFieldName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ce059f47-7ba5-497e-bbb0-d9b01c062c67",
            "sourceColumn": "VendorFieldName",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1793d5ca-88ea-4b02-91fc-e27da51b5a49",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "DisplayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "306d4059-aaf2-495e-bc82-0e16554a15e1",
            "sourceColumn": "DisplayName",
            "summarizeBy": "none"
          },
          {
            "name": "DisplayOrder",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4cc47610-9be2-4ff0-9dbc-8a618e63b104",
            "sourceColumn": "DisplayOrder",
            "summarizeBy": "sum"
          },
          {
            "name": "DataType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9ca2d89-5049-4898-92e6-b22910de98ae",
            "sourceColumn": "DataType",
            "summarizeBy": "none"
          },
          {
            "name": "DataFormat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79105fa8-ede9-4848-8c3d-625d323685e7",
            "sourceColumn": "DataFormat",
            "summarizeBy": "none"
          },
          {
            "name": "VendorId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "366a9c58-a995-4db8-ba70-68fa1d4b2b18",
            "sourceColumn": "VendorId",
            "summarizeBy": "count"
          },
          {
            "name": "KPI-Metrics",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "27836f77-41aa-4f03-bce3-dd60b7a21dd7",
            "sourceColumn": "KPI-Metrics",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9f22b587-caee-4b86-9e94-06e23560b452",
        "measures": [
          {
            "name": "Measure Star",
            "expression": "IF(COUNT(Query1[KPI-Metrics])<1, \"*\",MAX(Query1[FieldValue]))",
            "lineageTag": "8d27b724-a253-478c-b863-c62afb36c819"
          },
          {
            "name": "Star_2",
            "expression": [
              "",
              "VAR distinctValues = DISTINCT(Query1[FieldValue])",
              "RETURN",
              "    IF(",
              "        COUNT(Query1[KPI-Metrics]) < 1,",
              "        \"*\",",
              "        CONCATENATEX(distinctValues, Query1[FieldValue], \", \")",
              "    )"
            ],
            "lineageTag": "7a2b53e9-23d3-4c68-81b0-d4db85aafeeb"
          }
        ],
        "partitions": [
          {
            "name": "Query1",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"d1esginsightssqluse2.database.windows.net\", \"ESGVendorDB\", [Query=\" SELECT#(lf)#(tab)CFVT.CDPFieldValueTrackingId#(lf)#(tab),CFVT.GlobalCompanyId#(lf)#(tab),CFVT.FieldId#(lf)#(tab),CFVT.FieldValue#(lf)#(tab),CFVT.ReportedYear#(lf)#(tab),CFVT.UpdatedDate#(lf)#(tab),F.FieldName#(lf)#(tab),F.VendorFieldName#(lf)#(tab),F.Description#(lf)#(tab),F.DisplayName#(lf)#(tab),F.DisplayOrder#(lf)#(tab),F.DataType#(lf)#(tab),F.DataFormat#(lf)#(tab),F.VendorId#(lf)FROM [ESG].[CDPFieldValueTracking] CFVT#(lf)LEFT JOIN [ESG].[Field] F#(lf)#(tab)ON CFVT.FieldId = F.FieldId#(lf)WHERE F.FieldId IN #(lf)(#(lf)#(tab)513,#(lf)#(tab)514, #(lf)#(tab)515, #(lf)#(tab)516,#(lf)#(tab)517,#(lf)#(tab)518,#(lf)#(tab)519,#(lf)#(tab)520,#(lf)#(tab)521,#(lf)#(tab)522,#(lf)#(tab)523,#(lf)#(tab)524,#(lf)#(tab)525,#(lf)#(tab)526,#(lf)#(tab)527,#(lf)#(tab)528,#(lf)#(tab)529,#(lf) #(lf)#(tab)825,#(lf)#(tab)826,#(lf)#(tab)827,#(lf)#(tab)828,#(lf)#(tab)829,#(lf)#(tab)830,#(lf)#(tab)831,#(lf)#(tab)832,#(lf)#(tab)833,#(lf)#(tab)834,#(lf)#(tab)835,#(lf)#(tab)836,#(lf)#(tab)837,#(lf)#(tab)838,#(lf)#(tab)839,#(lf)#(tab)840,#(lf)#(tab)841#(lf)#(tab))\"]),",
                "    #\"Added Conditional Column\" = Table.AddColumn(Source, \"KPI-Metrics\", each if [FieldId] = 513 then \"Purchased goods and services \" else if [FieldId] = 514 then \"Capital goods\" else if [FieldId] = 515 then \"Fuel-and-energy-related activities \" else if [FieldId] = 516 then \"Upstream Transportation and distribution \" else if [FieldId] = 517 then \"Waste generated in operations \" else if [FieldId] = 518 then \"Business travel \" else if [FieldId] = 519 then \"Employee commuting \" else if [FieldId] = 520 then \"Upstream leased assets  \" else if [FieldId] = 521 then \"Downstream transportation and distribution\" else if [FieldId] = 522 then \"Processing of sold products \" else if [FieldId] = 523 then \"Use of sold products \" else if [FieldId] = 524 then \"End of life treatment of sold products \" else if [FieldId] = 525 then \"Downstream leased assets \" else if [FieldId] = 526 then \"Franchises\" else if [FieldId] = 527 then \"Investments\" else if [FieldId] = 528 then \"Other (upstream) \" else if [FieldId] = 529 then \"Other (downstream) \" else if [FieldId] = 825 then \"Purchased Goods And Services\" else if [FieldId] = 826 then \"Capital Goods\" else if [FieldId] = 827 then \"Fuel-And-Energy-Related Activities \" else if [FieldId] = 828 then \"Upstream Transportation and Distribution\" else if [FieldId] = 829 then \"Waste Generated in Operations\" else if [FieldId] = 830 then \"Business Travel\" else if [FieldId] = 831 then \"Employee Commuting\" else if [FieldId] = 832 then \"Upstream Leased Assets\" else if [FieldId] = 833 then \"Downstream Transportation and Distribution\" else if [FieldId] = 834 then \"Processing of Sold Products\" else if [FieldId] = 835 then \"Use of Sold Products\" else if [FieldId] = 836 then \"End of Life Treatment of Sold Products\" else if [FieldId] = 837 then \"Downstream Leased Assets\" else if [FieldId] = 838 then \".Franchises.\" else if [FieldId] = 839 then \".Investments.\" else if [FieldId] = 840 then \".Other (upstream).\" else if [FieldId] = 841 then \".Other (downstream).\" else null)",
                "in",
                "    #\"Added Conditional Column\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ed87b76b-8375-4c0c-9013-b9f8d4bca5f8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c05f82af-d758-4d75-a17c-2ec1cf5b0bb4",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "3f5179ff-99e9-4c19-b2e4-b586a3a9560a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f81481bc-49ca-4f7d-b771-e55118fd0b98",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "91e54587-a4fa-454b-b818-0d6c560291bf",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "66287597-306b-4050-a160-2ce01b501193",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f31f8728-f3ae-408f-b545-b15237f775bc",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "89ac4967-acb1-4e35-893e-dfde8ea0bb54",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d1846e11-c12f-4e0b-9c02-a71e32ce423e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a798acdd-3264-4e2e-aca1-72c0d9a494f6",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "5ccba128-6d3a-4370-b984-10b42f327b1f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "294b2a84-6b95-4e34-89c9-280aff04d0d7",
                "ordinal": 3
              }
            ],
            "lineageTag": "0eaef1eb-707d-48c8-84eb-96da0a2f3889"
          }
        ],
        "isHidden": true,
        "lineageTag": "bba36b8d-2239-4fca-ba27-f8386ebba671",
        "partitions": [
          {
            "name": "LocalDateTable_ed87b76b-8375-4c0c-9013-b9f8d4bca5f8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Query1'[UpdatedDate])), 1, 1), Date(Year(MAX('Query1'[UpdatedDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}